name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: mbianco/ghex:gcc-9

    steps:
      - uses: actions/checkout@v1
      - name: Configure
        run: |
          echo "WORKFLOW"
          env
          ulimit -a
          ipcs -lm
          mkdir -p build && cd build
          CXX=/usr/bin/g++ eckit_DIR=/opt/eckit Atlas_DIR=/opt/atlas cmake .. -DUCX_DIR=/usr/local -DGHEX_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DGHEX_ENABLE_ATLAS_BINDINGS=ON -DGHEX_USE_UCP=ON -DGHEX_BUILD_BENCHMARKS=OFF
      - name: Build
        run: cmake --build build --parallel 2
      - name: Execute tests
        run: cd build && env&&  ctest --verbose --output-on-failure	
